services:
        oap-frontend-client-deploy:
           command: sh -c "npm run start"
           build: 
              context: ./
              dockerfile: Dockerfile
              target: full
           working_dir: /usr/src/app/client-deploy
           volumes:
            - .:/usr/src/app/client-start:deploy
           ports:
             - "${DOCKER_PORT_OUT}:${DOCKER_PORT_IN}"